---
title: HackerBible

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  oneliners:
    output: true

defaults:
  - scope:
      path: '_oneliners'
    values:
      layout: bin
